version: '3.7'
services:
  nginx:
    image: nginx:1.23.2-alpine
    restart: unless-stopped
    volumes:
      - ./:/var/www/backend
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      args:
        user: user
        uid: 1000
      context: ./docker
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www/backend
    working_dir: /var/www/backend
    environment:
      XDEBUG_CONFIG: 'client_host=${XDEBUG_CLIENT_HOST} client_port=${XDEBUG_CLIENT_PORT}'
      PHP_IDE_CONFIG: 'serverName=DockerLaravel9'
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
    depends_on:
      - db

  db:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    ports:
      - "33061:3306"
